### PR TITLE
Added the ability to reset datatables when collection is reset 

### LINKED ISSUE #1: Listen for "reset" event on collection
Right now the module "only" listens for `add`, `remove`, and `change` events from the collection. It would be awesome if we had a way to listen to the `reset` event as well for cases when, say, one is doing a search and needs to completely reset the contents of the collection to a new/limited set of models.

I apologize if there's already a way to accomplish this without changing the module. I'd be happy to write the feature if you could give me some insight or tips on how it might be accomplished.

**EDIT**
I'm aware that having to re-draw the datatable completely might be expensive on large collections, but, maybe there's a way to do a diff between the new and old set of models? Sounds even more expensive, actually... hmmm...

### PR DESCRIPTION
**Pull request by kylefarris**
Also updated the Change Log in the readme.

Fixes #1

### CODE REVIEW

**Comment by cdaringe** [comment]
@kylefarris, added you as a collab.  merge whenever you're ready

**Comment by kylefarris** [comment]
Also updated to fix #3 .

**Comment by kylefarris** [comment]
Hey Chris, I'm not seeing the option to merge into master.

**Comment by cdaringe** [comment]
> Awaiting kylefarris' response

did you see the msg in your email?

**Comment by kylefarris** [comment]
Sorry man. Yeah, I see it now. Thanks.

**Comment by kylefarris** [comment]
Hey Chris, it's merged. I know you're probably busy, but, would you mind upping the minor and publishing to NPM?

**Comment by cdaringe** [comment]
i added you on NPM!

**Comment by kylefarris** [comment]
Haha, didn't even know you could do that. Thanks. I guess I'm the only one that uses this plugin, lol. Thanks for making it BTW.

**Comment by cdaringe** [comment]
ya sure thing!  my old team is still using it :)

**Pull request merged**
